DELETE FROM CUSTOMERS
WHERE CUSTOMER_ID = 4; -- ERROR CAUSE CUSTOMER_ID <=> TRANSACTIONS

-- ON DELETE SET NULL = when a FK is deleted, replace FK with null
ALTER TABLE TRANSACTIONS
DROP FOREIGN KEY transactions_ibfk_1;

ALTER TABLE TRANSACTIONS 
ADD CONSTRAINT FK_customer_id
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
ON DELETE SET NULL;

DELETE FROM CUSTOMERS WHERE CUSTOMER_ID = 4; -- SUCCESS 
-- => set CUSTOMER_ID transactions'row = NULL

-- ON DELETE CASCADE = when a FK is deleted, delete row
ALTER TABLE TRANSACTIONS 
ADD CONSTRAINT transactions_ibfk_1
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
ON DELETE CASCADE;

DELETE FROM CUSTOMERS WHERE CUSTOMER_ID = 4; -- SUCCESS 
-- => also delete transactions'rows if they had customer_id = 4

SELECT * FROM CUSTOMERS;