-- COLUMNS ---
-- add 1 column in table 
ALTER TABLE EMPLOYEES ADD PHONE_NUMBER VARCHAR(15);
-- change column name
ALTER TABLE EMPLOYEES RENAME COLUMN PHONE_NUMBER TO EMAIL;
-- change column datatype
ALTER TABLE EMPLOYEES MODIFY COLUMN EMAIL varchar(100);
-- move the column
ALTER TABLE EMPLOYEES MODIFY EMAIL varchar(100) AFTER LAST_NAME;
ALTER TABLE EMPLOYEES MODIFY EMAIL varchar(100) FIRST;
-- drop the column
ALTER TABLE EMPLOYEES DROP COLUMN EMAIL;
