-- primary key: not null, unique
CREATE TABLE TRANSACTIONS(
	TRANSACTION_ID INT PRIMARY KEY,
    AMOUNT decimal(4, 2)
);

ALTER TABLE TRANSACTIONS 
ADD CONSTRAINT PRIMARY KEY (TRANSACTION_ID);

INSERT INTO TRANSACTIONS 
VALUES (1000, 4.99),
		(1001, 2.89),
        (1002, 3.38),
        (1003, 4.99);
        
SELECT AMOUNT FROM TRANSACTIONS 
WHERE TRANSACTION_ID < 1100 AND TRANSACTION_ID > 1000;

DROP TABLE TRANSACTIONS;